### ISSUE TITLE
swagger 접근 시, 403 권한 에러

### ISSUE THREAD

**Issue by spacewalk00** [familymoments/family-moments-BE#122]
1. /swagger-ui `403 에러`
![image](https://github.com/familymoments/family-moments-BE/assets/97500298/78eb0e95-76dc-4a74-95fc-654e2c847cd1)
2. /swagger-ui/index.html# `200 OK`
![image](https://github.com/familymoments/family-moments-BE/assets/97500298/1c0fc421-c194-4a60-9960-6be1f1e78687)

WebConfig에 "/swagger-ui", "/swagger-ui/" 추가 해보았지만 여전히 에러 발생
로컬, 도메인 모두 동일 에러 확인함

**Comment by zzo3ozz** [comment]
오해였던 것으로,,,,
